nelec 12
spin 0
schedule
0     20  1.0000e-04  1.0000e-04
2     20  1.0000e-05  1.0000e-05
4     20  1.0000e-06  1.0000e-06
6     20  1.0000e-07  0.0000e+00
end
twodot_to_onedot 10
orbitals FCIDUMP
maxiter 18
sweep_tol 1.0000e-06
outputlevel 2
hf_occ integral
twopdm
prefix  /Users/nstair/Src/my_qforte/qforte/sandbox/cr2_pyscf_calcs/scratch_block2
